### ISSUE TITLE
Trajectory plot removes other plots from viewer in R Studio

### ISSUE THREAD

**Issue by slyles1001** [r-simmer/simmer.plot#17]
Plotting statistics, and then trajectories, will remove all plots besides the trajectories from the viewer pane in RStudio.

version info:
Package simmer.plot version 0.1.14

platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          5.1                         
year           2018                        
month          07                          
day            02                          
svn rev        74947                       
language       R                           
version.string R version 3.5.1 (2018-07-02)
nickname       Feather Spray

RStudio Version 1.1.456

**Comment by Enchufa2** [comment]
What do you mean by *remove*? Regular plots show in the "Plots" pane, while trajectories are diagrams, which show in the "Viewer" pane. After plotting a trajectory, you should be able to switch back to the "Plots" pane. And if not, that could be an RStudio bug, so I suggest you to open an issue there.

**Comment by slyles1001** [comment]
I'm sorry, I'm dumb for not noticing the switch to viewer tab. I'll close
the issue.
