### ISSUE TITLE
Avoid bypass edge for cloned trajectory

### ISSUE THREAD

**Issue by instantkaffee** [r-simmer/simmer.plot#6]
The plot of a trajectory which is has 3 cloned subtrajectories and cloning is done with n=3 Shows a bypath.
This is unintuitive.
Would it not be more intuitive if n=number of subtrajectories to exclude the Bypass ?

**Comment by Enchufa2** [comment]
Could you provide an example, please?

**Comment by instantkaffee** [comment]
```
library(simmer.plot)

t <- trajectory() %>%
  clone(n = 3,
        trajectory("original") %>%
          timeout(1),
        trajectory("clone 1") %>%
          timeout(2),
        trajectory("clone 2") %>%
          timeout(3)) %>%
  synchronize(wait = TRUE) 

plot(t)
```

![bildschirmfoto 2017-03-04 um 10 43 55](https://cloud.githubusercontent.com/assets/3050723/23577730/8377a3b0-00c7-11e7-8db7-d8faa3034ca3.png)

**Comment by Enchufa2** [comment]
It sounds reasonable. I will remove edges for ignored subtrajectories too (e.g., show the first two edges only if `n=2` in your example).
